import { Language } from '../types';

export const invoiceLabels: Record<Language, Record<string, string>> = {
  es: {
    invoiceTitle: 'Factura electrónica de venta',
    issuerData: 'Datos del Emisor',
    clientData: 'Datos del Cliente',
    issueDate: 'Fecha de emisión',
    dueDate: 'Fecha de vencimiento',
    item: 'Ítem',
    description: 'Descripción',
    quantity: 'Cantidad',
    unitPrice: 'Precio Unitario',
    total: 'Vr. Total',
    amountInWords: 'Valor en Letras',
    paymentTerms: 'Condiciones de Pago',
    observations: 'Observaciones',
    transferData: 'Datos para la transferencia',
    bankName: 'Nombre del Banco',
    bankAddress: 'Dirección del Banco',
    country: 'País',
    swiftCode: 'Código Swift Banco',
    accountOwner: 'Nombre completo del dueño de la cuenta',
    ibanNumber: 'Número de Cuenta IBAN',
    accountNumber: 'Numero de Cuenta y tipo',
    address: 'Dirección',
    totalToPay: 'Total a Pagar',
    paymentMethod: 'Forma de pago',
    footer: 'A esta factura de venta aplican las normas relativas a la letra de cambio (artículo 5 Ley 1231 de 2008). Con esta el Comprador declara haber recibido real y materialmente las mercancías o prestación de servicios descritos en este título - Valor. Número Autorización 18764030461654 aprobado en 20220623 prefijo LP desde el número 49 al 96 Vigencia: 24 - Actividad Económica Tarifa',
    accountOwnerAddress: 'Dirección del titular',
    routingNumber: 'Número de ruta',
  },
  en: {
    invoiceTitle: 'Electronic Sales Invoice',
    issuerData: 'Issuer Data',
    clientData: 'Client Data',
    issueDate: 'Issue Date',
    dueDate: 'Due Date',
    item: 'Item',
    description: 'Description',
    quantity: 'Quantity',
    unitPrice: 'Unit Price',
    total: 'Total',
    amountInWords: 'Amount in Words',
    paymentTerms: 'Payment Terms',
    observations: 'Observations',
    transferData: 'Transfer Data',
    bankName: 'Bank Name',
    bankAddress: 'Bank Address',
    country: 'Country',
    swiftCode: 'Bank Swift Code',
    accountOwner: 'Full name of account owner',
    ibanNumber: 'IBAN Account Number',
    accountNumber: 'Account Number and type',
    address: 'Address',
    totalToPay: 'Total to Pay',
    paymentMethod: 'Payment Method',
    footer: 'This sales invoice is subject to the regulations related to bills of exchange (Article 5 Law 1231 of 2008). With this, the Buyer declares to have received the goods or services described in this title - Value. Authorization Number 18764030461654 approved on 20220623 prefix LP from number 49 to 96 Validity: 24 - Economic Activity Rate',
    accountOwnerAddress: 'Account owner address',
    routingNumber: 'Routing Number',
  }
};

export const invoiceFixedValues = {
  bankName: 'Bank of America',
  bankAddress: '222 Broadway New York, New York 10038',
  country: 'USA',
  swiftCode: 'BOFAUS3N',
  accountOwner: 'LUIS ORLANDO MAURY SANCHEZ',
  ibanNumber: 'N/A',
  accountNumber: {
    es: 'Cuenta corriente No. 8980 2253 0922',
    en: 'Checking account No. 8980 2253 0922'
  },
  address: '12019 Suellen Circle, Wellington, FL, USA 33414',
  routingNumber: '026009593',
};