import { IssuerProfile, Language, TransferOptionProfile } from '../types';

export const invoiceLabels: Record<Language, Record<string, string>> = {
  es: {
    invoiceTitle: 'Factura electrónica de venta',
    issuerData: 'Datos del Emisor',
    clientData: 'Datos del Cliente',
    issueDate: 'Fecha de emisión',
    dueDate: 'Fecha de vencimiento',
    item: 'Ítem',
    description: 'Descripción',
    quantity: 'Cantidad',
    unitPrice: 'Precio Unitario',
    total: 'Vr. Total',
    amountInWords: 'Valor en Letras',
    paymentTerms: 'Condiciones de Pago',
    observations: 'Observaciones',
    transferData: 'Datos para la transferencia',
    bankName: 'Nombre del Banco',
    bankAddress: 'Dirección del Banco',
    country: 'País',
    swiftCode: 'Código Swift Banco',
    accountOwner: 'Nombre completo del dueño de la cuenta',
    accountNumber: 'Numero de Cuenta y tipo',
    address: 'Dirección',
    totalToPay: 'Total a Pagar',
    paymentMethod: 'Forma de pago',
    footer: '',
    accountOwnerAddress: 'Dirección del titular',
    routingNumber: 'Número de ruta',
    abaCode: 'Código ABA',
    transferOption: 'Opción de Transferencia',
  },
  en: {
    invoiceTitle: 'Electronic Sales Invoice',
    issuerData: 'Issuer Data',
    clientData: 'Client Data',
    issueDate: 'Issue Date',
    dueDate: 'Due Date',
    item: 'Item',
    description: 'Description',
    quantity: 'Quantity',
    unitPrice: 'Unit Price',
    total: 'Total',
    amountInWords: 'Amount in Words',
    paymentTerms: 'Payment Terms',
    observations: 'Observations',
    transferData: 'Transfer Data',
    bankName: 'Bank Name',
    bankAddress: 'Bank Address',
    country: 'Country',
    swiftCode: 'Bank Swift Code',
    accountOwner: 'Full name of account owner',
    accountNumber: 'Account Number and type',
    address: 'Address',
    totalToPay: 'Total to Pay',
    paymentMethod: 'Payment Method',
    footer: '',
    accountOwnerAddress: 'Account owner address',
    routingNumber: 'Routing Number',
    abaCode: 'ABA Code',
    transferOption: 'Transfer Option',
  }
};

// IMPORTANT: Sensitive data (issuers / bank accounts / legal notes) must never be shipped in the bundle.
// These catalogs are expected to live ONLY in the remote JSON.
export const defaultTransferOptionProfiles: TransferOptionProfile[] = [];

export const defaultIssuerProfiles: IssuerProfile[] = [];